### ISSUE TITLE
굿즈 구매

### ISSUE THREAD

**Issue by romandev** [gdgsuwon/devfest2018#12]
굿즈 디자인 확정 및 구매

**Comment by yjaeseok** [comment]
http://www.zerogift.com/product_w/product_view.asp?p_idx=165889 100개 색상 다양하게 디자인 진행필요

**Comment by yjaeseok** [comment]
일러스트 파일은 나연님께서 만들어주심 감사.

**Comment by yjaeseok** [comment]
우산은 발주 완료 100개 61만원 정도.

예산 대비 9만원 남음.

**Comment by romandev** [comment]
재석님에 의해 완료
