### ISSUE TITLE
구글의 지원 규모 문의

### ISSUE THREAD

**Issue by romandev** [gdgsuwon/devfest2018#15]
필요한 문서 작성 포함

**Comment by yjaeseok** [comment]
GDG Korea 이벤트 지원 요청 폼

https://docs.google.com/forms/d/e/1FAIpQLScl-ixUW1XU-c-KdbUqjYw_4VTU7Q2sqfGLMvXCwFp6vVGE9Q/viewform

**Comment by yjaeseok** [comment]
이벤트 지원 요청 완료,
지원규모 1인당 2만원
