### ISSUE TITLE
광교문화창조허브에 협조공문 발송

### ISSUE THREAD

**Issue by romandev** [gdgsuwon/devfest2018#2]

**Comment by romandev** [comment]
초기에 협조 공문 발송하였으나 프로그램 확정 후 다시 추가 발송 필요할 수 있음.
https://docs.google.com/document/d/1ruN2w9Hi5uqVQLrnClKHsgrxsBe2n_zWOUPVjCQRUZI/edit?usp=sharing

**Comment by yjaeseok** [comment]
발송했나요? 아직안보내도 되나요?

**Comment by romandev** [comment]
보냈는데 강태욱님에 컨펌이 없어서 유선상으로 컨펌 확정.

**Comment by jjakeyoon** [comment]
감사합니당!

**Comment by romandev** [comment]
아이디가 달라요..ㅋㅋ
